#!/bin/bash

while make && (
	git add . &&
	git commit -m WIP
	./build/Critty.app/Contents/MacOS/Critty "$@" || exit $?
); do :; done

./critty "%@"

#while :; do
#	git add . && git commit -m WIP
#	sleep 10
#done
