#!/usr/bin/env python

import hoisin
import sys

if len(sys.argv) == 1:
    target = '~'
elif len(sys.argv) == 2:
    target = sys.argv[1]
elif len(sys.argv) > 2:
    sys.stderr.write("usage: cd [dir]\n")
    sys.exit(1)

if not hoisin.cd(target):
    sys.exit(1)
