#!/usr/bin/env python

import hoisin
import sys

if len(sys.argv) == 1:
    target = '~'
elif len(sys.argv) == 2:
    target = sys.argv[1]
elif len(sys.argv) > 2:
    sys.stderr.write("usage: cd [dir]\n")
    sys.exit(1)

hoisin.send({ "cd": target })

def on_cd(success):
    if not success:
        sys.exit(1)

hoisin.recv(cd=on_cd)
